
package com.sf.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUploadImageAction", targetNamespace = "http://action.receiveserver.module.sf.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUploadImageAction {


    /**
     * 
     * @param passWord
     * @param imageStream
     * @param ip
     * @return
     *     returns java.lang.String
     * @throws WSException
     */
    @WebMethod
    @WebResult(partName = "return")
    public String uploadImage(
        @WebParam(name = "imageStream", partName = "imageStream")
        WaybillImageStream imageStream,
        @WebParam(name = "ip", partName = "ip")
        String ip,
        @WebParam(name = "passWord", partName = "passWord")
        byte[] passWord)
        throws WSException
    ;

}
