
package com.sf.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UploadImageActionService", targetNamespace = "http://action.receiveserver.module.sf.com/", wsdlLocation = "http://10.202.17.189:8089/ImageUploadService?wsdl")
public class UploadImageActionService
    extends Service
{

    private final static URL UPLOADIMAGEACTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException UPLOADIMAGEACTIONSERVICE_EXCEPTION;
    private final static QName UPLOADIMAGEACTIONSERVICE_QNAME = new QName("http://action.receiveserver.module.sf.com/", "UploadImageActionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.202.17.189:8089/ImageUploadService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UPLOADIMAGEACTIONSERVICE_WSDL_LOCATION = url;
        UPLOADIMAGEACTIONSERVICE_EXCEPTION = e;
    }

    public UploadImageActionService() {
        super(__getWsdlLocation(), UPLOADIMAGEACTIONSERVICE_QNAME);
    }

    public UploadImageActionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPLOADIMAGEACTIONSERVICE_QNAME, features);
    }

    public UploadImageActionService(URL wsdlLocation) {
        super(wsdlLocation, UPLOADIMAGEACTIONSERVICE_QNAME);
    }

    public UploadImageActionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPLOADIMAGEACTIONSERVICE_QNAME, features);
    }

    public UploadImageActionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UploadImageActionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IUploadImageAction
     */
    @WebEndpoint(name = "UploadImageActionPort")
    public IUploadImageAction getUploadImageActionPort() {
        return super.getPort(new QName("http://action.receiveserver.module.sf.com/", "UploadImageActionPort"), IUploadImageAction.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IUploadImageAction
     */
    @WebEndpoint(name = "UploadImageActionPort")
    public IUploadImageAction getUploadImageActionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://action.receiveserver.module.sf.com/", "UploadImageActionPort"), IUploadImageAction.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPLOADIMAGEACTIONSERVICE_EXCEPTION!= null) {
            throw UPLOADIMAGEACTIONSERVICE_EXCEPTION;
        }
        return UPLOADIMAGEACTIONSERVICE_WSDL_LOCATION;
    }

}
